### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by dt2patel** [hotwax/shopify-hc-oms-app#33]
The app installation and onboarding experience should be much smoother and better looking than it currently is.

Use the following Figma link to see what the proposed design should be:

https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=40657-93089&t=ON6X7Kiz8YDU5y3U-11

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
